# roles/base/tasks/main.yml
# Install baseline software and updates

# see https://github.com/ansible/ansible/issues/51663#issuecomment-1038843039
- name: Wait for the system to become reachable
  wait_for_connection:
    timeout: 600

- name: Wait for cloud-init / user-data to finish
  command: cloud-init status --wait
  changed_when: false

- name: Apply changes to /etc/inputrc (history-search-backward)
  lineinfile:
    path: /etc/inputrc
    regexp: '^#\s*.*history-search-backward'
    line: '"\e[5~": history-search-backward'

- name: Apply changes to /etc/inputrc (history-search-forward)
  lineinfile:
    path: /etc/inputrc
    regexp: '^#\s*.*history-search-forward'
    line: '"\e[6~": history-search-forward'

- name: Update the package list
  apt:
    update_cache: yes

- name: Install the baseline software
  apt:
    name:
      - wget
      - curl
      - vim
      - tmux
      - sudo
    state: latest

- name: Install updates
  apt:
    name: "*"
    state: latest
  register: reboot_needed

- name: Reboot after installing updates
  reboot:
  when: reboot_needed is changed

