--- # Main playbook 

- hosts: 127.0.0.1
  roles:
    - role: base
      become: yes
    - role: docker
      become: yes
    - role: build_dependencies
      become: yes
    - role: pyenv
      become: no
      tags: pyenv
