# roles/pyenv/tasks/main.yml
# Install pyenv + pyenv virtualenv (git clone)
# https://github.com/pyenv/pyenv#basic-github-checkout

- name: Make sure the directory .pyenv exists
  file:
    path: "{{ansible_env.HOME}}/.pyenv"
    state: directory

- name: Clone the pyenv repo
  git: 
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ansible_env.HOME}}/.pyenv"
    clone: yes
    accept_hostkey: yes
    force: yes

- name: Clone the pyenv-virtualenv repo
  git: 
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ansible_env.HOME}}/.pyenv/plugins/pyenv-virtualenv"
    clone: yes
    accept_hostkey: yes
    force: yes

- name: Setup the shell environment for pyenv + pyenv-virtualenv
  blockinfile:
    path: "{{ansible_env.HOME}}/.bashrc"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (pyenv/pyenv-virtualenv)"
