# roles/add_users/tasks/main.yml
# Create users, add to the relevant groups, add SSH keys

- name: Create the user and add it to the relevant groups
  user:
    name: "{{user}}"
    shell: /bin/bash
    groups: sudo, docker
    append: yes

- name: Make sure the directory .ssh exists
  file:
    path: "{{user_home}}/.ssh"
    state: directory
    owner: "{{user}}"
    group: "{{user}}"
    mode: '0700'

- name: Copy authorized_keys from root
  copy:
    src: /root/.ssh/authorized_keys
    dest: "{{user_home}}/.ssh/authorized_keys"
    owner: "{{user}}"
    group: "{{user}}"
    remote_src: yes
