--- # Main playbook 

- hosts: all
  vars:
    user: "gc"
    user_home: "/home/{{user}}"
    git_username: "CHANGEME"
    git_email: "CHANGEME@users.noreply.github.com"
  roles:
    - role: base
      become: yes
    - role: docker
      become: yes
    - role: add_users
      become: yes
    - role: build_dependencies
      become: yes
    - role: pyenv
      become: yes
      become_user: "{{user}}"
      tags: pyenv
    - role: user-config
      become: yes
      become_user: "{{user}}"
      tags: user-config
