--- # Main playbook 

- hosts: all
  roles:
    - role: base
      become: yes
    - role: add_users
      become: yes
    - role: docker
      become: yes
    - role: build_dependencies
      become: yes
    - role: pyenv
      become: no
      tags: pyenv
