# roles/base/tasks/main.yml
# Install baseline software and updates

- name: install baseline software
  apt:
    name:
      - wget
      - curl
      - vim
      - tmux
    state: latest
    update_cache: yes
- name: install updates
  apt:
    name: "*"
    state: latest
    update_cache: yes
